function translate(metric) {
  translation = {
    "goldUsage": "la media ponderada entre el oro gastado y el oro obtenido",
    "inhibitorKills": "inhibidores destruidos",
    "baronNashorAssist": "asistencias en Barones Nashor",
    "deaths": "muertes",
    "damageDealtToObjectives": "daño inflingido a objetivos",
    "assists": "asistencias",
    "totalDamageTaken": "daño total recibido",
    "dragonKills": "dragones asesinados",
    "damageSelfMitigated": "daño mitigado a uno mismo",
    "damageDealtToBuildings": "daño inflingido a estructuras",
    "consumablesPurchased": "consumibles comprados",
    "baronKills": "Barones Nashor asesinados",
    "minionEfficiency": "la proporción de súbditos asesinados en tu línea",
    "kills": "asesinatos",
    "totalDamageDealt": "daño total realizado",
    "visionScore": "puntiación de visión",
    "turretKills": "torretas destruidas",
    "trueDamageTaken": "daño verdadero recibido",
    "trueDamageDealtToChampions": "daño verdadero inflingido a campeones",
    "trueDamageDealt": "daño verdadero inflingido",
    "totalUnitsHealed": "aliados totales curados",
    "totalMinionsKilled": "súbditos totales asesinados",
    "totalHealsOnTeammates": "curaciones totales a aliados",
    "totalHeal": "curación total",
    "perfectDragonSoulsTaken": "almas de dragón sin que el enemigo asesine ningún dragón",
    "bountyGold": "recompensa de oro al final de la partida",
    "pickKillWithAlly": "asesinatos contra enemigos con ayuda de un aliado",
    "epicMonsterSteals": "monstruos épicos robados",
    "epicMonsterStolenWithoutSmite": "monstruos épicos robados sin smite",
    "getTakedownsInAllLanesEarlyJungleAsLaner": "asesinatos de todas las posiciones en todas las líneas antes del minuto 10 (excepto jungla)",
    "enemyJungleMonsterKills": "monsturos de la jungla enemiga asesinados",
    "initialBuffCount": "buffs de la jungla antes del minuto 10",
    "initialCrabCount": "cangrejos asesinados de los 2 primeros",
    "epicMonsterKillsNearEnemyJungler": "monstruos épicos asesinados cerca del jungla enemigo",
    "enemyChampionImmobilizations": "número de inmobilizaciones de campeones enemigos",
    "elderDragonMultikills": "asesinatos múltiples con Dragón Anciano",
    "effectiveHealAndShielding": "curación y escudos efectivos",
    "kTurretsDestroyedBeforePlatesFall": "torretas destruidas antes de que caigan las placas",
    "completeSupportQuestInTime": "misión del objeto de soporte completada a tiempo",
    "buffsStolen": "buffs robados",
    "blastConeOppositeOpponentCount": "uso de la piña explosiva para redireccionar a un oponente y al jugador en direcciones opuestas",
    "alliedJungleMonsterKills": "monstruos de la jungla aliados asesinados",
    "junglerTakedownsNearDamagedEpicMonster": "asesinatos del jungla enemigo cerca de monstruos épicos dañados",
    "turretPlatesTaken": "placas de torreta obtenidas",
    "firstTurretKilledTime": "segundos transcurridos antes de destruir la primera torreta",
    "turretsTakenWithRiftHerald": "torretas destruidas con Heraldo",
    "fullTeamTakedown": "asesinatos completos del equipo enemigo",
    "totalDamageShieldedOnTeammates": "daño mitigado proporcionando escudo a aliados",
    "totalDamageDealtToChampions": "daño total realizado a campeones",
    "timeCCingOthers": "tiempo de CC proporcionado",
    "minionsConceeded": "porcentaje de súbditos concedidos al ADC aliado"
  };
  return translation[metric];
}
